modLoader="javafml"
loaderVersion="${forge_loader_requirement}"
license="MIT"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="NTTS Plugin"
logoFile="icon.png"
credits=""
authors="nny"
description='''
A plugin integration with TTS service /N/TTS
'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_requirement}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version}]"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="voicechat"
    mandatory=true
    versionRange="[${voicechat_dependency},)"
    ordering="AFTER"
    side="BOTH"