minecraft_version=1.21.11
java_version=21
pack_format=94
build_generation=ping_9

fabric_loader_version=0.18.1
fabric_api_version=0.141.5+1.21.11
fabric_minecraft_requirement=~1.21.11
fabric_voicechat_artifact=fabric-1.21.11-2.6.7

forge_version=61.1.0
forge_loader_requirement=[61,)
forge_requirement=[61.1.0,)
forge_reobf=false

voicechat_dependency_version=1.21.11-2.6.7
