minecraft_version=1.21.8
java_version=21
pack_format=64
build_generation=doggyman

fabric_loader_version=0.16.14
fabric_api_version=0.136.1+1.21.8
fabric_minecraft_requirement=~1.21.8
fabric_voicechat_artifact=fabric-1.21.8-2.5.34

forge_version=58.1.0
forge_loader_requirement=[58,)
forge_requirement=[58.1.0,)
forge_reobf=false
forge_eventbus=7

voicechat_dependency_version=1.21.8-2.5.34
