minecraft_version=26.2
java_version=25
pack_format=107
build_generation=unlimited_damage

fabric_loader_version=0.19.3
fabric_api_version=0.155.2+26.2
fabric_minecraft_requirement=~26.2
fabric_voicechat_artifact=fabric-2.6.18+26.2

forge_version=65.0.7
forge_loader_requirement=[65,)
forge_requirement=[65.0.7,)
forge_reobf=false

voicechat_dependency_version=2.6.18+26.2
